# ----
# Site

title: ControlH
url: https://github.com/jpunn/jpunn.github.io.git
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Jekyll template with example content for a not-for-profit organisation.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Cause Template
  links:
    - https://github.com/CloudCannon/cause-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd7a3QIuY0ImYT6HFwU6cgehpiUSY1pdnMHXr3Fg2e7J_nGGw/viewform?embedded=true" height="685px" width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="yes"></iframe>'
newsletter_action: '<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd7a3QIuY0ImYT6HFwU6cgehpiUSY1pdnMHXr3Fg2e7J_nGGw/viewform?embedded=true" width="640" height="975" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
